export default [
  {
    bg: '#A8DDE9',
    color: '#3F5B98',
    category: 'Simple present',
    subCategories: [' Regular Action: I come here daily.',
    '   Irregular Action: Earthquake comes in Japan.',
    '   Habits: He smokes, I never drink coffee before 12.00.',
    '  Universal Truth: The sun rises in the East.',
    ' (Note: In newspaper headlines and commentary of sports, Simple present tense is used.)'
],
  },
    {
    bg: '#FECBCA',
    color: '#FD5963',
    category: 'Simple Past',
    subCategories: ['   1. Last year I took my exams.',
    '   2. I got married in 1992.',
    '   3. Last year, I traveled to Japan.' ,
    '   4. She had a baby last year.',
    '   5. Did you have dinner last night?',
    '   6. She washed her car.',
    '   7. I saw a movie yesterday.'
    
],
  },
    {
    bg: '#A8DDE9',
    color: '#3F5B98',
    category: 'Simple Future',
    subCategories: ['   1. We will paint our house next week.',
    '   2. They will write the letter to their best friend.',
    '   3. He will close the shop.' ,
    '   4. She will see her friend at the weekend.',
    '   5. They will be here in two hours.',
    '   6. He will help you tomorrow.',
    '   7. They are going to dance.'],
  },

  {
    bg: '#A8DDE9',
    color: '#3F5B98',
    category: 'Present Continuous',
    subCategories: ['   1. I am writing articles on different topics.',
    '   2. He is reading various kinds of books.',
    '   3. I am listening to melodious songs.' ,
    '   4. They are playing cricket in that field.',
    '   5. The poet is writing romantic poems',
    '   6. Are you watching cricket on television?',
    '   7. I am helping him to do the task.'],
    
  },
  
  {
    bg: '#FECBCA',
    color: '#FD5963',
    category: 'Past Continuous',
    subCategories: ['   1. She was drinking coffee in that coffee shop.',
    '   2. He was practicing to sing the song for the program.',
    '   3. I was writing articles on different topics.' ,
    '   4. We were enjoying the program thoroughly.',
    '   5. You were shopping in that market.',
    '   6. Were you watching tele drama on television?',
    '   7. I was not watching the cricket match on television.'],
  },
    {
    bg: '#A8DDE9',
    color: '#3F5B98',
    category: 'Future Continuous',
    subCategories: ['   1. Mahesh will be reading various kinds of books.',
    '   2. Bob will be going to the library.',
    '   3. The poet will be writing a poem for the program.' ,
    '   4. Robin will be joining us at the meeting.',
    '   5. He will be doing his job.',
    '   6. We will be going to enjoy the musical drama.',
    '   7. I will be arranging all the necessary materials.'],
  },
   {
    bg: '#FD5963',
    color: '#123B8C',
    category: 'present perfect',
    subCategories: ['   1. We have watched movies in this Cineplex.',
    '   2. He has traveled around the world.',
    '   3. They have played cricket in that field.' ,
    '   4. I have watched this movie on television.',
    '   5. The poet has written romantic poems.',
    '   6. Have you helped him to do his project?',
    '   7. Have you listened to realistic songs?'],
  },
   {
    bg: '#FD5963',
    color: '#A8DDE9',
    category: 'Past perfect',
    subCategories: ['   1. He had read different kinds of books.',
    '   2. She had listened to melodious songs',
    '   3. I had practiced the songs before the program started.' ,
    '   4. The lyricist had come to the program.',
    '   5. He had not practiced the game.',
    '   6. Mahesh had traveled around the world',
    '   7. Had you come to the program before I came?'],
  },
   {
    bg: '#FD5963',
    color: '#193B8C',
    category: 'future perfect',
    subCategories: ['   1. Robert will have read various kinds of books.',
    '   2. You will have shopped at that market before we come.',
    '   3. I will have sung many songs before you join us.' ,
    '   4. I will not have attended the program',
    '   5. I will have arranged all the necessary materials',
    '   6. They will have helped him to do the task.',
    '   7. I will have attended the program before I come here.'],
  },
  {
    bg: '#193B8C',
    color: '#FECBCD',
    category: 'present perfect Continuous',
    subCategories: ['   1. They have been playing football for an hour.',
    '   2. He has been traveling around the world for a month.',
    '   3. I have been watching the concert for two days.' ,
    '   4. I have been helping him to do the task for an hour.',
    '   5. The poet has been writing some poems for two hours.',
    '   6. He has been traveling around the world for a month.',
    '   7. She has been finding the dress since morning.'],
  },
  {
    bg: '#193B8C',
    color: '#FD5963',
    category: 'past perfect Continuous',
    subCategories: ['   1. I had been writing articles for three hours.',
    '   2. We had been enjoying the program for days.',
    '   3. I had been shopping with him in the fair since morning' ,
    '   4. They had been playing hockey on that field for one day.',
    '   5. I had been listening to melodious songs for two hours.',
    '   6. Tom had been gossiping in the shop since morning.',
    '   7. She had been singing songs for an hour.'],
  
  },
   {
    bg: '#193B8C',
    color: '#F5F5EB',
    category: 'Future Perfect Continuous',
    subCategories: ['   1. Robert will have been read various kinds of books.',
    '   2. You will have been shopped at that market before we come.',
    '   3. I will have been sung many songs before you join us.' ,
    '   4. I will not have  been attended the program',
    '   5. I will have been arranged all the necessary materials',
    '   6. They will have been helped him to do the task.',
    '   7. I will have been attended his leture '],
  
  },
  

];