export default [
  
    {
    bg: '#69d2e7',
    color: '#FD5560',
    category: 'Thanks so much.',
    subCategories: [' This is a simple sentence you can use to thank someone',
    '   To add detail, say:',
    '   Thanks so much + for + [noun] / [-ing verb].' ,
    '   For example:',
    '   ⚪ Thanks so much for the birthday money.',
    '   ⚪ Thanks so much for driving me home.',
],
},
    {
    bg: '#a7dbd8',
    color: '#3F5B98',
    category: 'I really appreciate…',
    subCategories: ['   You can also use this phrase to thank someone.',
    '   For example, you might say:',
    '   ⚪ I really appreciate your help.',
    '         Or you can combine #1 and #2: ',
    '   ⚪ Thanks so much for cooking dinner. I really appreciate', 
    '         it.',
    '   ⚪ Thanks so much. I really appreciate you cooking dinner.',
    ],
  },

  {
    bg: '#e0e4cc',
    color: '#3F5B98',
    category: 'Excuse me',
    subCategories: ['   When you need to get through but there’s someone',
    '   blocking your way, say “Excuse me.”',
    '   You can also say this phrase to politely get someone’s', 
    '   attention.     For example:',
    '   ⚪ Excuse me sir, you dropped your wallet.' ,
    '   ⚪ Excuse me, do you know what time it is?',
    ],
    
  },
  
  {
    bg: '#FECBCA',
    color: '#FD5963',
    category: 'I’m sorry',
    subCategories: ['   Use this phrase to apologize, whether for something',
    '   big or small. ',
    '   Use “for” to give more detail. For example:',
    '   ⚪ I’m sorry for being so late.',
    '   ⚪ I’m sorry for the mess. I wasn’t expecting anyone today.',
    'You can use “really” to show you’re very sorry for something:',
    '   ⚪ I’m really sorry I didn’t invite you to the party.',
    ],
  },
    {
    bg: '#A8DDE9',
    color: '#3F5B98',
    category: 'What do you think?',
    subCategories: ['   When you want to hear someone’s opinion on a topic,',
    '   use this question.',
    '   ⚪ I’m not sure if we should paint the room yellow or blue.', 
    '         What do you think?',
    ],
  },
   {
    bg: '#fc9d9a',
    color: '#3F5B90',
    category: 'How does that sound?',
    subCategories: ['   If you suggest an idea or plan, use this phrase to find out', 
    '   what others think.',
    '   ⚪ We could have dinner at 6, and then go to a movie.', 
    '         How does that sound?',
    '   ⚪ Let’s hire a band to play music, and Brent can', 
    '         photograph the event. How does that sound?'
  ],
  },
{
    bg: '#FD5560',
    color: '#3F5B98',
    category: ' Could you repeat please?',
    subCategories: ['   We can say “please” either at the end of the question or', 
    '   right after “you,” like this:',
    '   ⚪ Could you please repeat that?',
    '   ⚪ Could you repeat that please?' ,
  ],
  },
 
];